#!name=淘宝短视频屏蔽
#!desc=看你妈短视频啊
#!src=https://raw.githubusercontent.com/
#!author=Junyi-99
#!notes=Chekout the github repo: https://github.com/Junyi-99/ShadowrocketModules

[MITM]
hostname = %APPEND% *.cloudvideocdn.taobao.com, *.alicdn.com, 
# *.tanx.com, *.taobao.com, *.alibabachengdun.com


[Rule]

# 淘宝视频
# URL-REGEX,^https?:\/\/.*cloudvideocdn\.taobao\.com\/.*\.mp4.*,REJECT
DOMAIN-SUFFIX,cloudvideocdn.taobao.com,REJECT

# 淘宝直播聊天
# https://impaas.alicdn.com/live/message/cb23d75d-b92b-4dff-b2c3-604130f64b43/1706107311/1706107315?deviceId=YuvZ/G6QlsQDANkEGRmIafit
URL-REGEX,^https?:\/\/.*alicdn\.com\/.*live.*,REJECT

# 淘宝其他
DOMAIN-SUFFIX,acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,agoo-report.m.taobao.com,REJECT
DOMAIN-SUFFIX,xjp-jmacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,adashx4ae.ut.taobao.com,REJECT
DOMAIN-SUFFIX,audid-api-sg.taobao.com,REJECT
DOMAIN-SUFFIX,h-adashx.ut.taobao.com,REJECT
DOMAIN-SUFFIX,guide-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,umengacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,amdcopen.m.taobao.com,REJECT
DOMAIN-SUFFIX,umengjmacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,amdc.m.taobao.com,REJECT
DOMAIN-SUFFIX,xjp-msgacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,adashx4sg.ut.taobao.com,REJECT
DOMAIN-SUFFIX,accscdn.m.taobao.com,REJECT
DOMAIN-SUFFIX,trade-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,ip.taobao.com,REJECT
DOMAIN-SUFFIX,h-adashx4ae.ut.taobao.com,REJECT
DOMAIN-SUFFIX,eco.taobao.com,REJECT
DOMAIN-SUFFIX,err.taobao.com,REJECT
DOMAIN-SUFFIX,baichuan-sdk.taobao.com,REJECT
DOMAIN-SUFFIX,mamasearchad.cloudvideocdn.taobao.com,REJECT
DOMAIN-SUFFIX,retcode.taobao.com,REJECT
DOMAIN-SUFFIX,guangguang.cloudvideocdn.taobao.com,REJECT
DOMAIN-SUFFIX,gaode-jmacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,dualstack-na610-na620.acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,h-adashx4sg.ut.taobao.com,REJECT
DOMAIN-SUFFIX,sjarvis.taobao.com,REJECT
DOMAIN-SUFFIX,gaode-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,tunion-api.m.taobao.com,REJECT
DOMAIN-SUFFIX,ea119.amdc.m.taobao.com,REJECT
DOMAIN-SUFFIX,adashx4yt.m.taobao.com,REJECT
DOMAIN-SUFFIX,area.amdc.m.taobao.com,REJECT
DOMAIN-SUFFIX,re.taobao.com,REJECT
DOMAIN-SUFFIX,adashbc.m.taobao.com,REJECT
DOMAIN-SUFFIX,show.re.taobao.com,REJECT
DOMAIN-SUFFIX,acs4baichuan.m.taobao.com,REJECT
DOMAIN-SUFFIX,taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,textlink.simba.taobao.com,REJECT
DOMAIN-SUFFIX,cloudvideocdn.taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,taobao.com.itotolink.net,REJECT
DOMAIN-SUFFIX,tns.simba.taobao.com,REJECT
DOMAIN-SUFFIX,s.click.taobao.com,REJECT
DOMAIN-SUFFIX,h-adashx4bc.ut.taobao.com,REJECT
DOMAIN-SUFFIX,m.taobao.com.itotolink.net,REJECT
DOMAIN-SUFFIX,tbs-vsucai.cloudvideocdn.taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,tui.taobao.com,REJECT
DOMAIN-SUFFIX,youku-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,openjmacs.m.taobao.com,REJECT
DOMAIN-SUFFIX,xjp-jmacs.m.taobao.com.itotolink.net,REJECT
DOMAIN-SUFFIX,pcookie.taobao.com,REJECT
DOMAIN-SUFFIX,audid-api-sg.taobao.com.itotolink.net,REJECT
DOMAIN-SUFFIX,h-adashx4yt.ut.taobao.com,REJECT
DOMAIN-SUFFIX,ald.taobao.com,REJECT
DOMAIN-SUFFIX,video-zb.cloudvideocdn.taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,odin.re.taobao.com,REJECT
DOMAIN-SUFFIX,ai.m.taobao.com,REJECT
DOMAIN-SUFFIX,click.mz.simba.taobao.com,REJECT
DOMAIN-SUFFIX,redirect.simba.taobao.com,REJECT
DOMAIN-SUFFIX,video-sh.cloudvideocdn.taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,click.simba.taobao.com,REJECT
DOMAIN-SUFFIX,advertisement.taobao.com.gds.alibabadns.com,REJECT
DOMAIN-SUFFIX,wagbridge.advertisement.taobao.com.gds.alibabadns.com,REJECT
DOMAIN-SUFFIX,ai.taobao.com,REJECT
DOMAIN-SUFFIX,na61-na62.wagbridge.advertisement.taobao.com.gds.alibabadns.com,REJECT
DOMAIN-SUFFIX,count.taobao.com,REJECT
DOMAIN-SUFFIX,m.taobao.com.queniuak.com,REJECT
DOMAIN-SUFFIX,wb.110.taobao.com,REJECT
DOMAIN-SUFFIX,acookie.taobao.com,REJECT
DOMAIN-SUFFIX,amos1.taobao.com,REJECT
DOMAIN-SUFFIX,bcfeedback.taobao.com,REJECT
DOMAIN-SUFFIX,g.click.taobao.com,REJECT
DOMAIN-SUFFIX,global.click.taobao.com,REJECT
DOMAIN-SUFFIX,ju.taobao.com,REJECT
DOMAIN-SUFFIX,adash-c.m.taobao.com,REJECT
DOMAIN-SUFFIX,baichuan.m.taobao.com,REJECT
DOMAIN-SUFFIX,sdkinit.taobao.com,REJECT
DOMAIN-SUFFIX,shop115048570.taobao.com,REJECT
DOMAIN-SUFFIX,simaba.taobao.com,REJECT
DOMAIN-SUFFIX,m.simaba.taobao.com,REJECT
DOMAIN-SUFFIX,dsp.simba.taobao.com,REJECT
DOMAIN-SUFFIX,fav.simba.taobao.com,REJECT
DOMAIN-SUFFIX,m.simba.taobao.com,REJECT
DOMAIN-SUFFIX,mclick.simba.taobao.com,REJECT
DOMAIN-SUFFIX,srd.simba.taobao.com,REJECT
DOMAIN-SUFFIX,stat.simba.taobao.com,REJECT
DOMAIN-SUFFIX,click.tz.simba.taobao.com,REJECT
DOMAIN-SUFFIX,tejia.taobao.com,REJECT
DOMAIN-SUFFIX,temai.taobao.com,REJECT
DOMAIN-SUFFIX,top.taobao.com,REJECT
DOMAIN-SUFFIX,tyh.taobao.com,REJECT
DOMAIN-SUFFIX,adash.ut.taobao.com,REJECT
DOMAIN-SUFFIX,adashx.ut.taobao.com,REJECT
DOMAIN-SUFFIX,adash-c.ut.taobao.com,REJECT
DOMAIN-SUFFIX,log.video.taobao.com,REJECT
DOMAIN-SUFFIX,acs.wapa.taobao.com,REJECT
DOMAIN-SUFFIX,wdm.taobao.com,REJECT


DOMAIN-SUFFIX,httpdns.alicdn.com,REJECT
DOMAIN-SUFFIX,userlink.alicdn.com,REJECT
DOMAIN-SUFFIX,dorangesource.alicdn.com,REJECT
DOMAIN-SUFFIX,yixiu-abtest.alicdn.com,REJECT
DOMAIN-SUFFIX,ilce.alicdn.com,REJECT
DOMAIN-SUFFIX,baichuan-sdk.alicdn.com,REJECT
DOMAIN-SUFFIX,pss.alicdn.com,REJECT
DOMAIN-SUFFIX,ialicdn.com,REJECT
DOMAIN-SUFFIX,nbsdk-baichuan.alicdn.com,REJECT
DOMAIN-SUFFIX,appdownload.alicdn.com,REJECT
DOMAIN-SUFFIX,client.ialicdn.com,REJECT
DOMAIN-SUFFIX,ldns.ialicdn.com,REJECT
DOMAIN-SUFFIX,player-msl.ialicdn.com,REJECT
DOMAIN-SUFFIX,asearch.alicdn.com,REJECT
DOMAIN-SUFFIX,wwwwebalicdn.xxdingrui.com,REJECT
DOMAIN-SUFFIX,proxy-mob-cld.alicdn.com,REJECT
DOMAIN-SUFFIX,atanx.alicdn.com,REJECT
DOMAIN-SUFFIX,umc.danuoyi.alicdn.com,REJECT
DOMAIN-SUFFIX,alicdn.com.itotolink.net,REJECT
DOMAIN-SUFFIX,atanx2.alicdn.com,REJECT
DOMAIN-SUFFIX,oalipay-dl-django.alicdn.com,REJECT
DOMAIN-SUFFIX,gma.alicdn.com,REJECT
DOMAIN-SUFFIX,g01.a.alicdn.com,REJECT
DOMAIN-SUFFIX,aecpm.alicdn.com,REJECT
DOMAIN-SUFFIX,afpmm.alicdn.com,REJECT
DOMAIN-SUFFIX,alimama.alicdn.com,REJECT
DOMAIN-SUFFIX,handycam.alicdn.com,REJECT
DOMAIN-SUFFIX,img.im.alicdn.com,REJECT
DOMAIN-SUFFIX,kb-render.alicdn.com,REJECT
DOMAIN-SUFFIX,strip.alicdn.com,REJECT
DOMAIN-SUFFIX,unidesk.alicdn.com,REJECT
DOMAIN-SUFFIX,alicdn.bayimob.com,REJECT

DOMAIN-SUFFIX,alibabachengdun.com,REJECT
DOMAIN-SUFFIX,umdc.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,mum.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,cdn-mum.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,acs-mum.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,vip-bgp-umdc.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,vip-bgp-mum.alibabachengdun.com,REJECT
DOMAIN-SUFFIX,vip-cmcc-mum.alibabachengdun.com,REJECT